server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age: 86400

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useUnicode=true&amp&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: io.github.lamprose.bookshell.dao
  check-config-location: true
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:log4j2.xml

